[package]
name = "nyks-p2p"
description = "p2p types of nyks"
authors = ["Triton Software"]
version = "0.8.0"
edition = "2024"
license = "Apache-2.0"

repository = "https://github.com/Nyksnet/nyksnode/"

[dependencies]
itertools = "0.14"
tasm-lib = "9.0.0"
anyhow = { version = "1.0", features = ["backtrace"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.10"
num-traits = "0.2"
tracing = "0.1"
thiserror = "1.0.65"
num-bigint = { version = "0.4", features = ["serde"] }
libp2p = { version = "0.56.0", features = [] }
arraystring = { version = "0.3.0", features = ["serde-traits"] }
sha2 = "0.10.9"
semver = "^1.0.23"
nyks-consensus = { version = "0.8.0", path = "../consensus" }

[dev-dependencies]

[lints]
workspace = true

