name: Tests

on: [ push, pull_request ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Set up cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check --tests --workspace

  test:
    name: Test Suite
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    strategy:
      fail-fast: false
      # matrix:
      #   os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Set up cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        run: cargo test --workspace

  lints:
    name: Lints
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: 1.97.1
          components: rustfmt, clippy

      - name: Set up cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --workspace --tests -- -D warnings
